disabled_rules:
- unused_optional_binding
- force_cast
opt_in_rules:
- closure_spacing
- empty_count
- empty_string
- let_var_whitespace
- operator_usage_whitespace
- vertical_whitespace_closing_braces
- vertical_whitespace_opening_braces
excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib
identifier_name:
    min_length: # only min_length
        warning: 2 # only error
    excluded: # excluded via string array
        - id
        - URL
        - GlobalAPIKey
trailing_whitespace:
    ignores_empty_lines: true
line_length:
    warning: 200
    error: 300
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
function_body_length:
    warning: 300
    error: 500
function_parameter_count:
    warning: 6
    error: 8
type_body_length:
    warning: 300
    error: 500
file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true
cyclomatic_complexity:
    warning: 15
    error: 25
nesting:
    type_level:
        warning: 3
    statement_level:
        warning: 5
reporter: "xcode"

